# Generated by Django 3.0.7 on 2025-02-27 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_auto_20250227_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='state',
            field=models.CharField(choices=[('P1', 'Koshi'), ('P2', 'Madhesh'), ('P3', 'Bagmati'), ('P4', 'Gandaki'), ('P5', 'Lumbini'), ('P6', 'Karnali'), ('P7', 'Sudurpashchim')], max_length=100),
        ),
    ]
